name: .NET Core

on:
  push:
    branches: [ master, linux-bbox ]
  pull_request:
    branches: [ master, linux-bbox ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.810
    - name: Install dependencies
      run: dotnet restore
      working-directory: src
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: src
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: src
